import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
  name: appTarget.targetName,
  projects: [
    "App",
    "Core",
    "Components",
    "NoteEditorFeature",
    "NotesListFeature"
  ],
  generationOptions: .options(
    autogeneratedWorkspaceSchemes: .disabled,
    lastXcodeUpgradeCheck: Version(26, 1, 0)
  )
)
