import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
  name: appTarget.targetName,
  projects: [
    "App",
    "Core",
    "Components",
    "FeatureA",
    "FeatureB"
  ],
  generationOptions: .options(
    autogeneratedWorkspaceSchemes: .disabled,
    lastXcodeUpgradeCheck: Version(26, 1, 0)
  )
)
