import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
  name: appTarget.targetName,
  projects: [
    "App",
    "Core",
    "Components",
    "NoteEditorFeature",
    "NotesListFeature"
  ],
  schemes: [
    // Aggregates every module's tests into one run-all surface. A project-level
    // scheme can only reference its own project's targets, so this lives at the
    // workspace level. Use with `tuist test AllTests` or select it in Xcode.
    .scheme(
      name: "AllTests",
      shared: true,
      testAction: .targets(
        [
          .testableTarget(target: .project(path: "App", target: "\(appTarget.targetName)Tests")),
          .testableTarget(target: .project(path: "Core", target: "CoreTests")),
          .testableTarget(target: .project(path: "Components", target: "ComponentsTests")),
          .testableTarget(
            target: .project(path: "NotesListFeature", target: "NotesListFeatureTests")
          ),
          .testableTarget(
            target: .project(path: "NoteEditorFeature", target: "NoteEditorFeatureTests")
          )
        ],
        configuration: "Debug"
      )
    )
  ],
  generationOptions: .options(
    autogeneratedWorkspaceSchemes: .disabled,
    lastXcodeUpgradeCheck: Version(26, 1, 0)
  )
)
